### ISSUE TITLE
unit-quickcheck 0.4-beta-2 not compatible with junit 4.11

### ISSUE THREAD

**Issue by PascalSchumacher** [pholser/junit-quickcheck#41]
Hi Paul, 

thanks a lot for creating junit-quickcheck. :)

I do not know if it is intentional, but junit-quickcheck version 0.4-beta-2, does not seem to work with junit version 4.11. If I try to run it (e.g. GeographyTheories example) I get:

java.lang.NoClassDefFoundError: org/junit/AssumptionViolatedException
    at org.junit.contrib.theories.Theories$TheoryAnchor$1.methodBlock(Theories.java:160)
    at org.junit.contrib.theories.Theories$TheoryAnchor.runWithCompleteAssignment(Theories.java:153)
    at org.junit.contrib.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:142)
    at org.junit.contrib.theories.Theories$TheoryAnchor.runWithIncompleteAssignment(Theories.java:148)
    at org.junit.contrib.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:140)
    at org.junit.contrib.theories.Theories$TheoryAnchor.evaluate(Theories.java:128)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.junit.AssumptionViolatedException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 21 more

If I use junit version 4.12-beta-2 it works like a charm.
